// <auto-generated />
using GitHub.Pages.Writer.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GitHub.Pages.Writer.API.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20230119061340_SeedCategoryData")]
    partial class SeedCategoryData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("GitHub.Pages.Writer.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Programming",
                            Name = "Programming",
                            ParentID = 0,
                            Slug = "programming"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Life",
                            Name = "Life",
                            ParentID = 0,
                            Slug = "life"
                        },
                        new
                        {
                            Id = 3,
                            Description = "As if you cared",
                            Name = "as-if-you-cared",
                            ParentID = 0,
                            Slug = "as-if-you-cared"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Professional Geek",
                            Name = "professional_geek",
                            ParentID = 0,
                            Slug = "professional-geek"
                        },
                        new
                        {
                            Id = 5,
                            Description = "RSSBandit",
                            Name = "rssbandit",
                            ParentID = 0,
                            Slug = "rssbandit"
                        },
                        new
                        {
                            Id = 6,
                            Description = "PostXing",
                            Name = "postxing",
                            ParentID = 0,
                            Slug = "postxing"
                        },
                        new
                        {
                            Id = 7,
                            Description = ".NET",
                            Name = "dotnet",
                            ParentID = 0,
                            Slug = "dotnet"
                        },
                        new
                        {
                            Id = 8,
                            Description = "C#",
                            Name = "csharp",
                            ParentID = 0,
                            Slug = "csharp"
                        },
                        new
                        {
                            Id = 9,
                            Description = "WinForms",
                            Name = "winforms",
                            ParentID = 0,
                            Slug = "winforms"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Visual Studio",
                            Name = "visual_studio",
                            ParentID = 0,
                            Slug = "visual-studio"
                        },
                        new
                        {
                            Id = 11,
                            Description = "ASP.NET",
                            Name = "aspnet",
                            ParentID = 0,
                            Slug = "aspnet"
                        },
                        new
                        {
                            Id = 12,
                            Description = "BlogML",
                            Name = "BlogML",
                            ParentID = 0,
                            Slug = "blogml"
                        },
                        new
                        {
                            Id = 13,
                            Description = "SubSonic",
                            Name = "SubSonic",
                            ParentID = 0,
                            Slug = "subsonic"
                        },
                        new
                        {
                            Id = 14,
                            Description = "JavaScript",
                            Name = "javascript",
                            ParentID = 0,
                            Slug = "javascript"
                        },
                        new
                        {
                            Id = 15,
                            Description = "DataGridView",
                            Name = "DataGridView",
                            ParentID = 0,
                            Slug = "datagridview"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Subversion",
                            Name = "subversion",
                            ParentID = 0,
                            Slug = "subversion"
                        },
                        new
                        {
                            Id = 17,
                            Description = "SVN",
                            Name = "svn",
                            ParentID = 0,
                            Slug = "svn"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Apache",
                            Name = "apache",
                            ParentID = 0,
                            Slug = "apache"
                        },
                        new
                        {
                            Id = 19,
                            Description = "xUnit",
                            Name = "xunit",
                            ParentID = 0,
                            Slug = "xunit"
                        },
                        new
                        {
                            Id = 20,
                            Description = "StructureMap",
                            Name = "StructureMap",
                            ParentID = 0,
                            Slug = "structuremap"
                        },
                        new
                        {
                            Id = 21,
                            Description = "SQLite",
                            Name = "SQLite",
                            ParentID = 0,
                            Slug = "sqlite"
                        },
                        new
                        {
                            Id = 22,
                            Description = "MVC",
                            Name = "mvc",
                            ParentID = 0,
                            Slug = "mvc"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Standard",
                            Name = "Standard",
                            ParentID = 0,
                            Slug = "standard"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Stencil",
                            Name = "stencil",
                            ParentID = 0,
                            Slug = "stencil"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Street Art",
                            Name = "streetart",
                            ParentID = 0,
                            Slug = "streetart"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Same",
                            Name = "same",
                            ParentID = 0,
                            Slug = "same"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Image",
                            Name = "Image",
                            ParentID = 0,
                            Slug = "image"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Rake",
                            Name = "rake",
                            ParentID = 0,
                            Slug = "rake"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Geek",
                            Name = "geek",
                            ParentID = 0,
                            Slug = "geek"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Music",
                            Name = "music",
                            ParentID = 0,
                            Slug = "music"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Travel",
                            Name = "travel",
                            ParentID = 0,
                            Slug = "travel"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Puerto Rico",
                            Name = "puerto_rico",
                            ParentID = 0,
                            Slug = "puerto-rico"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Ruby",
                            Name = "ruby",
                            ParentID = 0,
                            Slug = "ruby"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Math",
                            Name = "math",
                            ParentID = 0,
                            Slug = "math"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Personal",
                            Name = "personal",
                            ParentID = 0,
                            Slug = "personal"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Albacore",
                            Name = "albacore",
                            ParentID = 0,
                            Slug = "albacore"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Windows",
                            Name = "Windows",
                            ParentID = 0,
                            Slug = "windows"
                        },
                        new
                        {
                            Id = 38,
                            Description = "GRUB",
                            Name = "grub",
                            ParentID = 0,
                            Slug = "grub"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Linux",
                            Name = "linux",
                            ParentID = 0,
                            Slug = "linux"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Jekyll",
                            Name = "jekyll",
                            ParentID = 0,
                            Slug = "jekyll"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Liquid",
                            Name = "liquid",
                            ParentID = 0,
                            Slug = "liquid"
                        },
                        new
                        {
                            Id = 42,
                            Description = "GitHub Pages",
                            Name = "github-pages",
                            ParentID = 0,
                            Slug = "github-pages"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Git",
                            Name = "git",
                            ParentID = 0,
                            Slug = "git"
                        },
                        new
                        {
                            Id = 44,
                            Description = "ZSH",
                            Name = "zsh",
                            ParentID = 0,
                            Slug = "zsh"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Philosophy",
                            Name = "Philosophy",
                            ParentID = 0,
                            Slug = "philosophy"
                        },
                        new
                        {
                            Id = 46,
                            Description = "Ruby",
                            Name = "Ruby",
                            ParentID = 0,
                            Slug = "ruby"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Linux",
                            Name = "Linux",
                            ParentID = 0,
                            Slug = "linux"
                        },
                        new
                        {
                            Id = 48,
                            Description = "Unbuntu",
                            Name = "Unbuntu",
                            ParentID = 0,
                            Slug = "unbuntu"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Programming",
                            Name = "Programming",
                            ParentID = 0,
                            Slug = "programming"
                        },
                        new
                        {
                            Id = 50,
                            Description = "gh-pages",
                            Name = "gh-pages",
                            ParentID = 0,
                            Slug = "gh-pages"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
